# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('problem_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField(max_length=10000)),
                ('difficulty', models.IntegerField()),
                ('example', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('submission_number', models.IntegerField(default=0)),
                ('accept_number', models.IntegerField(default=0)),
                ('acceptance', models.FloatField(default=0)),
                ('accept_user_number', models.IntegerField(default=0)),
                ('hint', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='problemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'problem_tag',
            },
        ),
    ]
