# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 06:32
from __future__ import unicode_literals

import Record.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('item_id', models.CharField(default=Record.models.default_product_id, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='image/')),
                ('serial_no', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('report_no', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('pieces', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('main_material_name', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('main_stone_name', models.CharField(blank=True, max_length=50, null=True)),
                ('main_stone_weight', models.CharField(blank=True, max_length=20, null=True)),
                ('general_information', models.CharField(blank=True, max_length=1000, null=True)),
                ('supplier', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('net_price', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_price', models.CharField(blank=True, max_length=20, null=True)),
                ('discount', models.CharField(default='100', max_length=4)),
                ('store_name', models.CharField(default='#', max_length=20)),
                ('wholesale', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='sales_record',
            fields=[
                ('trade_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('trade_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f')),
                ('item_id', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.CharField(default='100', max_length=10)),
                ('trade_price', models.CharField(blank=True, max_length=20, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_personnel', models.CharField(blank=True, max_length=50, null=True)),
                ('wholesale', models.BooleanField(default=False)),
                ('store_name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
