# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=b'1491622624', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='permission',
            field=models.CharField(default='3', max_length=1),
        ),
    ]
