# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0003_auto_20170408_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=b'1491623268', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
