# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0004_auto_20170408_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=b'1491659634', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='cart',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
