# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0006_auto_20170408_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=b'1491660770', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='cart',
            field=models.CharField(blank=True, default='#', max_length=1000),
        ),
    ]
