# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0008_auto_20170408_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=b'1492010054', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
