# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0011_auto_20170414_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=b'1492150773', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
