# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0017_auto_20170414_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=b'1492158884', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
