# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndUser', '0020_auto_20170422_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=b'1492851045', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
