# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import submission.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.CharField(db_index=True, default=submission.models.rand_str, max_length=32, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_index=True, max_length=30)),
                ('problem_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('time_used', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=6)),
                ('res', models.IntegerField(default=8)),
                ('memory_used', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-create_time', 'problem_id'],
                'db_table': 'submission',
            },
        ),
    ]
